Ensure bfill/ffill leave no residual NaNs in the dataset
ludwig-ai/ludwig pull request #2553
Opened 2022-09-26 18:19 UTC by arnavgarg1

2022-09-26 20:19 UTC, justinxzhao approved these changes

2022-09-26 21:06 UTC, tgaddair requested changes

2022-09-26 21:06 UTC, tgaddair commented on ludwig/data/preprocessing.py
> +        if is_dask_series(dataset_cols[feature[COLUMN]]):
We should be using `backend` for this:

```
backend.compute(dataset_cols[feature[COLUMN]].isna().sum())
```

2022-09-26 21:06 UTC, tgaddair commented on ludwig/utils/dataframe_utils.py
> +def is_dask_series(series) -> bool:
Please remove this and use the Backend abstraction.

2022-09-26 23:44 UTC, justinxzhao approved these changes

2022-09-26 23:44 UTC, justinxzhao commented on tests/integration_tests/utils.py
> +) -> pd.DataFrame:
Let's add a docstring to briefly describe how the columns are used.

2022-09-27 17:07 UTC, tgaddair approved these changes

2022-09-27 18:10 UTC, merged