Log warning for failed ray imports
ludwig-ai/ludwig pull request #2589
Opened 2022-10-04 07:16 UTC by arnavgarg1

I started running into some bespoke test failures and figured out it was because the version of Ray I was using in my container was different from the version now officially supported by Ludwig (Ray >= 1.13). 

I realized that we don't actually log warnings when an import to ray fails and we also set this to None, which often causes downstream issues for tests in particular when we do a `ray.init()` call using test fixtures.

This PR logs warnings to make sure users running their tests are made of ray import failures.

2022-10-04 16:38 UTC, tgaddair requested changes
Not sure we want these warnings. The issue here is that these files get imported regardless of whether the user has ray installed, selected the ray backend, or anything else. So imagine a user who runs `pip install ludwig` and then just wants to train something. With these changes, they will see a warning even though they're not doing anything wrong. So we shouldn't confuse them by giving them warnings when there's no issue.

2022-10-04 16:41 UTC, arnavgarg1 commented
@tgaddair I see, I didn't realize that.

I think a better fix then might be to catch `ray.init()` calls within Ludwig to ensure that ray is not None when making that call and provide a more informative logging message there if it is. How does that sound? Otherwise it throws an error with something like `NoneType object has no method init`

2022-10-04 19:40 UTC, tgaddair commented
@arnavgarg1 definitely we should be raising appropriate errors if the user is trying to do something with ray but ray isn't installed, etc. Can you provide a repro for the behavior you're describing? I'm not sure I know the specific issue being addressed.

2022-10-05 04:58 UTC, arnavgarg1 commented
@tgaddair Can't seem to repro the error I was running into anymore. It was something along the lines of me trying to do something with Ray but the Ray import failing (Ray didn't exist), so it set `ray = None` silently. Then, when I tried to run one of the tests, it just said `NoneType object has no attribute init()`. I was just trying to make sure the error would make sense/have more context in case this ever came up again for anyone else. 

Will just close this issue for now.

2022-10-05 04:58 UTC, closed without merging