fix: Remove extra properties from `input_features`, `output_features`, `defaults` schemas for GBM models
ludwig-ai/ludwig pull request #2902
Opened 2023-01-06 07:32 UTC by ksbrar

Removes extra properties from the features and defaults schemas that are otherwise unsupported by GBM.

In particular
* `encoder` and `decoder` sub schemas are removed
* Only GBM-supported feature types are left behind after pruning the defaults schema
* Extra fields with references to encoders/decoders are removed: `input_size`, 'top_k`, `num_classes` - can I get a double check on this?

2023-01-06 07:41 UTC, arnavgarg1 commented
@ksbrar Looks good! I think `num_classes` and `top_k` might be ok though since we can do multiclass classification using GBMs?

2023-01-07 22:07 UTC, tgaddair requested changes
I feel like GBMs have a lot of special-cases in the schema. Is there not an object-oriented way to achieve this by creating custom subschemes for ECD and GBM?

2023-01-08 00:06 UTC, ksbrar commented
@tgaddair Sure, and I agree. As I made these changes I also felt they were suboptimal. This was initially scoped as an "on-call"-sized fix so I just tried to make a minimal change, but I can reformulate this PR.

2023-01-08 00:08 UTC, tgaddair commented
Hmm, I suppose if this is breaking something at the moment, we can land it as-is, but I want to think of a more longterm fix as well. We can sync up about it early next week. Thanks for looking into it!

2023-01-08 19:53 UTC, tgaddair commented on ludwig/schema/features/utils.py
> +                if k not in ["encoder", "decoder", "tied", "input_size", "num_classes", "top_k"]
GBMs will support encoders and decoders in #2896.

2023-01-08 19:53 UTC, tgaddair commented on ludwig/schema/defaults/defaults.py
> +    gbm_feature_types = ["binary", "category", "number"]
GBMs will support text features in #2896.

2023-01-08 20:08 UTC, ksbrar commented
@tgaddair What is the timeline for #2896 getting merged in? If it's soon I might just cancel this PR. Then we can sync on the refactoring necessary to enable a more robust/many-to-many encoder interface.

2023-01-09 23:26 UTC, ksbrar commented
Closed in favor of #2896

2023-01-09 23:26 UTC, closed without merging