Skip test_ray_outputs
ludwig-ai/ludwig pull request #2935
Opened 2023-01-14 04:08 UTC by arnavgarg1

This is a flaky test, skipping for now. 

I run into mismatch delayed errors. 

```
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `pandas.core.frame.DataFrame`
+----------------------------+--------+----------------------------------------+
| Column                     | Found  | Expected                               |
+----------------------------+--------+----------------------------------------+
| 'set_57C49_predictions'    | object | TensorDtype(shape=(4,), dtype=int64)   |
| 'set_57C49_probabilities'  | object | TensorDtype(shape=(4,), dtype=float32) |
| 'vector_C1424_predictions' | object | TensorDtype(shape=(5,), dtype=float32) |
+----------------------------+--------+----------------------------------------+
```

https://github.com/ludwig-ai/ludwig/issues/2889

2023-01-16 20:47 UTC, tgaddair requested changes
File an issue, and mark is as the reason for skipping.

2023-01-20 18:26 UTC, jeffkinnison approved these changes

2023-01-20 18:32 UTC, tgaddair approved these changes

2023-01-20 18:33 UTC, justinxzhao approved these changes

2023-01-20 18:33 UTC, merged