Disallow certain config parameters from accepting `null` as a value
ludwig-ai/ludwig pull request #3079
Opened 2023-02-11 07:27 UTC by abidwael

2023-02-12 20:27 UTC, tgaddair commented on ludwig/schema/hyperopt/executor.py
> +        default=3600, allow_none=True, description="The number of seconds for the entire hyperopt run."
Hmm, shouldn't `None` here correspond to "no time limit"?

2023-02-12 20:28 UTC, tgaddair commented on ludwig/schema/utils.py
> +    allow_none: bool = False,
Having default of `None` is.contradictory. If we remove `None`, we should choose a different default.

2023-02-12 20:28 UTC, tgaddair commented on ludwig/schema/utils.py
> +    allow_none: bool = False,
Same as above.

2023-02-12 20:29 UTC, tgaddair commented on ludwig/schema/utils.py
> +    allow_none = allow_none or default is None
This is too implicit. I prefer making it explcit on the caller side. If `allow_none` is `False` they must choose a non-null default.

2023-02-12 20:30 UTC, tgaddair commented on ludwig/schema/utils.py
> +    allow_none: bool = False,
Same as above.

2023-02-12 20:30 UTC, tgaddair commented on ludwig/schema/utils.py
> +    allow_none: bool = False,
Same as above. Note that you can make `default` a required param if needed.

2023-02-12 20:31 UTC, tgaddair requested changes
General feedback is that it's confusing to both have `None` be the default and `allow_none=False`. I would suggest either:

- Making `allow_none=True` the default
- Making `default` a required param

2023-02-13 08:18 UTC, abidwael commented
Makes sense @tgaddair.

I made `default` a required param and kept `allow_none=False` so we don't run into the same problem when for other parameters in the config or when we add new parameters. I did this for most of the config parameter types (all except `Dict`, `List`, and `DictList`). I kept the rest as they are because it seems like lots of them (if not all) have `default=None` in the schema. These could be schemafied and that way the default values could live in the schema instead of the model initialization code.

2023-02-14 20:00 UTC, justinxzhao approved these changes

2023-02-14 20:01 UTC, tgaddair commented on ludwig/schema/utils.py
> +    # allow_none = allow_none or default is None
Please remove commented code.

2023-02-14 20:01 UTC, tgaddair commented on ludwig/schema/utils.py
> +    # allow_none = allow_none or default is None
Remove.

2023-02-14 20:01 UTC, tgaddair commented on tests/integration_tests/test_model_training_options.py
> +    # assert train_losses[last_entry - 1] <= train_losses[0]
Remove.

2023-02-14 20:02 UTC, tgaddair approved these changes
LGTM, only nit is to remove the dead code you commented out.

2023-02-14 21:52 UTC, merged