Disable passthrough decoder
ludwig-ai/ludwig pull request #3151
Opened 2023-02-27 16:13 UTC by arnavgarg1

Ludwig Issue: https://github.com/ludwig-ai/ludwig/issues/3150

2023-02-27 16:20 UTC, tgaddair approved these changes

2023-02-27 20:56 UTC, w4nderlust commented
so for binary and number it makes sense and we should keep it, for everything else we can remove it

2023-03-02 21:20 UTC, abidwael requested changes
Could we disable passthrough decoder altogether for now and re-enable when we include the dot product combiner. 
cc: @w4nderlust

2023-03-02 23:04 UTC, abidwael approved these changes
Thanks @arnavgarg1!

2023-03-03 00:57 UTC, merged